### PR TITLE
feat: add `useSafeArea` to `showCustomDialog` method in `DialogService`

### PR DESCRIPTION
**Pull request by saileshbro**

### CODE REVIEW

**Review by FilledStacks — DISMISSED** [review]
Nice addition

**Comment by FilledStacks** [comment]
@ferrarafer can you apply the dart format fix update here too please.

**Comment by ferrarafer** [comment]
@saileshbro please, run the following command and push the changes, then I will merge the PR. Thanks for the collaboration 🔥 

`dart format --fix .`

**Comment by saileshbro** [comment]
@ferrarafer fixed lint issues.

**Pull request merged**
