### PR TITLE
Add barrierColor property to custom bottom sheet implementation

### PR DESCRIPTION
**Pull request by OgunwoleOluwatobi**
Added the barrier Color property passed in the showCustomSheet object to the implementation

### CODE REVIEW

**Review by FilledStacks — CHANGES_REQUESTED** [review]
Nice. Happy with the PR. We don't need to add the changelog version anymore. You can remove that. It will be added automatically with our fancy new CI setup 😄

**Comment by OgunwoleOluwatobi** [comment]
> Nice. Happy with the PR. We don't need to add the changelog version anymore. You can remove that. It will be added automatically with our fancy new CI setup 😄

Oh great. I looked up other PR to make sure i was doing things right. Very nice addition! 💪🏻

**Review by FilledStacks — APPROVED** [review]
Awesome!

**Comment by ferrarafer** [comment]
Hi @buehler ! Sorry to bother you again 😅 .

Do you know why version was bumped to `0.9.11` when the previous version was `1.0.0` ?

[CHANGELOG](https://github.com/Stacked-Org/services/blob/main/CHANGELOG.md)

**Comment by buehler** [comment]
Hey @ferrarafer
Yes. You (Dane as far as I know) published the version 1.0.0 manually and there is no v1.0.0 tag in the git repository.

**Comment by ferrarafer** [comment]
Oh, I see... thanks!

**Pull request merged**
